quarkus:
  http:
    port: 18080
  datasource:
    jdbc:
      driver: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/realworld
#      url: jdbc:mysql://quarkus-kotlin-realworld-db:3306/realworld
    username: root
    password: 1234
  hibernate-orm:
    log:
      sql: true
    database:
      generation: drop-and-create
  jacoco:
    reuse-data-file: true
    excludes: [
      "**/util/**",
      "**/dto/**"
    ]
  smallrye-jwt:
    enabled: true
  native:
    resources:
      includes: true
mp:
  jwt:
    verify:
      issuer: https://realworld.io
      publicly:
        location: publicKey.pem
    expiration:
      time:
        minutes: 10
smallrye:
  jwt:
    sign:
      key:
        location: privateKey.pem
    expiration:
      time:
        minutes: 10
bcrypt:
  hash:
    cost: 5